// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VarnavinaEkaterinaKt_31_22.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250426090951_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.AcademicGroup", b =>
                {
                    b.Property<int>("AcademicGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("academic_group_id")
                        .HasComment("Идентификатор записи академической группы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcademicGroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_group_name")
                        .HasComment("Название академической группы");

                    b.HasKey("AcademicGroupId")
                        .HasName("pk_cd_academic_group_academic_group_id");

                    b.HasIndex(new[] { "Name" }, "idx_cd_academic_group_group_name");

                    b.ToTable("AcademicGroups");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Performance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("performance_id")
                        .HasComment("Идентификатор записи успеваемости");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceId"));

                    b.Property<double>("Grade")
                        .HasColumnType("double precision")
                        .HasColumnName("grade")
                        .HasComment("Оценка студента");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed")
                        .HasComment("Статус прохождения предмета");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор студента");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id")
                        .HasComment("Идентификатор предмета");

                    b.HasKey("PerformanceId")
                        .HasName("pk_cd_performance_performance_id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор записи студента");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("AcademicGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_firstname")
                        .HasComment("Имя студента");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer")
                        .HasColumnName("group_id")
                        .HasComment("Идентификатор записи группы");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("s_student_lastname")
                        .HasComment("Фамилия студента");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("s_student_middlename")
                        .HasComment("Отчество студента");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_student_student_id");

                    b.HasIndex("AcademicGroupId");

                    b.HasIndex(new[] { "GroupID" }, "idx_cd_student_fk_f_group_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subject_id")
                        .HasComment("Идентификатор записи предмета");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_subject_name")
                        .HasComment("Название предмета");

                    b.HasKey("SubjectId")
                        .HasName("pk_cd_subject_subject_id");

                    b.HasIndex(new[] { "SubjectName" }, "idx_cd_subject_subject_name");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Performance", b =>
                {
                    b.HasOne("VarnavinaEkaterinaKt_31_22.Models.Student", "Student")
                        .WithMany("Performances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cd_performance_student_id");

                    b.HasOne("VarnavinaEkaterinaKt_31_22.Models.Subject", "Subject")
                        .WithMany("Performances")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cd_performance_subject_id");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Student", b =>
                {
                    b.HasOne("VarnavinaEkaterinaKt_31_22.Models.AcademicGroup", null)
                        .WithMany("Students")
                        .HasForeignKey("AcademicGroupId");

                    b.HasOne("VarnavinaEkaterinaKt_31_22.Models.AcademicGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.AcademicGroup", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Student", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("VarnavinaEkaterinaKt_31_22.Models.Subject", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
